/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ztl_SerialPort */

#ifndef _Included_ztl_SerialPort
#define _Included_ztl_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ztl_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;III)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_ztl_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     ztl_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ztl_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
